# Generated by Django 5.0.3 on 2024-03-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consumer", unique_together={("name", "ssn", "agency")},
        ),
    ]
