# Generated by Django 5.0.3 on 2024-03-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_manager", "0003_alter_consumer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="balance_manager.consumer",
            ),
        ),
    ]
